package ro.softronic.mihai.ro.papagodriver.Model;


import io.realm.RealmObject;

public class Order extends RealmObject {

//    @PrimaryKey
//    private int id;

    private String status;
    private String restaurant;
    private String client_latitude;
    private String client_longitude;
    private long expirationTime;

    public Order(){

    }
    //    public  Order(int id, String restaurant){
//        this.id = id;
//        this.restaurant = restaurant;
//    }
    public  Order(String restaurant, long expirationTime){
        this.restaurant = restaurant;
        this.expirationTime = expirationTime;
    }
    // Standard getters & setters generated by your IDE…
//    public int getId() {
//        return id;
//    }
//
//    public void setId(int id) {
//        this.id = id;
//    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRestaurant() {
        return restaurant;
    }

    public void setRestaurant(String restaurant) {
        this.restaurant = restaurant;
    }

    public String getClient_latitude(){
        return client_latitude;
    }

    public void setClient_latitude(String client_latitude){
        this.client_latitude = client_latitude;
    }

    public String getClient_longitude(){
        return client_longitude;
    }

    public void setClient_longitude(String client_longitude){
        this.client_longitude = client_latitude;
    }

    public void setExpirationTime(long expirationTime){
        this.expirationTime = expirationTime;
    }
    public  long getExpirationTime(){
        return this.expirationTime;
    }

}
